[default]
extend-ignore-re = [
    "Versionx",
    "versionx",
    "versiond",
    "rmcp",
    "toml_edit",
    "blake3",
    "Blake3",
    "BLAKE3",
    "pnpm",
    "uv",
    "sigstore",
    "octocrab",
    "mlua",
    "luau",
    "Luau",
    "gix",
    "git2",
    "rusqlite",
    "camino",
    "foojay",
    "Temurin",
    "corepack",
    "rustup",
    "changesets",
    "conventionalcommits",
    "PEP 440",
    "SHA-256",
    "SHA256",
]
