//! `versionx activate <shell>` — emit a shell snippet that puts the shim dir
//! at the front of `PATH`.
//!
//! For 0.1.0 this is a simple text emission; the spec's shell-hook-starts-daemon
//! behavior will be added when the daemon lands in 0.3.

use serde::Serialize;

use super::CoreContext;
use crate::error::CoreResult;

#[derive(Copy, Clone, Debug, Serialize)]
pub enum Shell {
    Bash,
    Zsh,
    Fish,
    Pwsh,
}

#[derive(Clone, Debug)]
pub struct ActivateOptions {
    pub shell: Shell,
}

/// Produce the shell snippet. `Ok(String)` so frontends can print it raw.
///
/// # Errors
/// Currently infallible — wrapped in `Result` for forward-compat.
#[allow(clippy::unnecessary_wraps)] // Kept `Result<>` for forward-compat — hooks may need to fail.
pub fn activate(ctx: &CoreContext, opts: &ActivateOptions) -> CoreResult<String> {
    let shims = ctx.home.shims_dir();
    Ok(match opts.shell {
        Shell::Bash | Shell::Zsh => format!(
            "# Versionx shell integration. Generated by `versionx activate`.\n\
             case \":${{PATH}}:\" in\n\
             \x20\x20*:{shims}:*) ;;\n\
             \x20\x20*) export PATH=\"{shims}:$PATH\" ;;\n\
             esac\n",
        ),
        Shell::Fish => format!(
            "# Versionx shell integration. Generated by `versionx activate`.\n\
             if not contains {shims} $PATH\n\
             \x20\x20\x20\x20set -gx PATH {shims} $PATH\n\
             end\n",
        ),
        Shell::Pwsh => format!(
            "# Versionx shell integration. Generated by `versionx activate`.\n\
             if ($env:PATH -split [IO.Path]::PathSeparator -notcontains '{shims}') {{\n\
             \x20\x20\x20\x20$env:PATH = '{shims}' + [IO.Path]::PathSeparator + $env:PATH\n\
             }}\n",
        ),
    })
}
