//! `versionx activate <shell>` — emit a shell snippet that:
//!   1. Prepends the shim dir to `PATH` (idempotent).
//!   2. Starts `versiond` in the background if it isn't already running
//!      (fire-and-forget — the daemon auto-binds its socket, and the next
//!      versionx call picks it up).
//!
//! The shell snippet is intentionally quiet (no stderr on startup) so it
//! doesn't pollute MOTD-sensitive shells. Users debugging the daemon run
//! `versionx daemon logs` instead.

use serde::Serialize;

use super::CoreContext;
use crate::error::CoreResult;

#[derive(Copy, Clone, Debug, Serialize)]
pub enum Shell {
    Bash,
    Zsh,
    Fish,
    Pwsh,
}

#[derive(Clone, Debug)]
pub struct ActivateOptions {
    pub shell: Shell,
}

/// Produce the shell snippet. `Ok(String)` so frontends can print it raw.
///
/// # Errors
/// Currently infallible — wrapped in `Result` for forward-compat.
#[allow(clippy::unnecessary_wraps)] // Kept `Result<>` for forward-compat — hooks may need to fail.
pub fn activate(ctx: &CoreContext, opts: &ActivateOptions) -> CoreResult<String> {
    let shims = ctx.home.shims_dir();
    Ok(match opts.shell {
        Shell::Bash | Shell::Zsh => format!(
            "# Versionx shell integration. Generated by `versionx activate`.\n\
             case \":${{PATH}}:\" in\n\
             \x20\x20*:{shims}:*) ;;\n\
             \x20\x20*) export PATH=\"{shims}:$PATH\" ;;\n\
             esac\n\
             # Start the daemon quietly if it's not already running.\n\
             command -v versionx >/dev/null 2>&1 && versionx daemon start >/dev/null 2>&1 &\n\
             disown 2>/dev/null || true\n",
        ),
        Shell::Fish => format!(
            "# Versionx shell integration. Generated by `versionx activate`.\n\
             if not contains {shims} $PATH\n\
             \x20\x20\x20\x20set -gx PATH {shims} $PATH\n\
             end\n\
             # Start the daemon quietly if it's not already running.\n\
             if type -q versionx\n\
             \x20\x20\x20\x20versionx daemon start >/dev/null 2>&1 &\n\
             \x20\x20\x20\x20disown 2>/dev/null\n\
             end\n",
        ),
        Shell::Pwsh => format!(
            "# Versionx shell integration. Generated by `versionx activate`.\n\
             if ($env:PATH -split [IO.Path]::PathSeparator -notcontains '{shims}') {{\n\
             \x20\x20\x20\x20$env:PATH = '{shims}' + [IO.Path]::PathSeparator + $env:PATH\n\
             }}\n\
             # Start the daemon quietly if it's not already running.\n\
             if (Get-Command versionx -ErrorAction SilentlyContinue) {{\n\
             \x20\x20\x20\x20Start-Process -WindowStyle Hidden -FilePath versionx -ArgumentList 'daemon','start' | Out-Null\n\
             }}\n",
        ),
    })
}
