//! Events catalog generator.
//!
//! Event kinds are not enumerated as Rust variants — they're dot-separated
//! strings passed to `EventSender::emit` / `::info` / `::warn` and to
//! `Event::new(...)`. We recover the catalog by scanning every `.rs` file
//! in `crates/` for these callsites, collecting the string-literal kind,
//! grouping by top-level category (the part before the first dot), and
//! de-duplicating.

use std::collections::{BTreeMap, BTreeSet};

use anyhow::{Context, Result};
use camino::Utf8Path;
use regex::Regex;
use walkdir::WalkDir;

use super::banner;

pub(super) fn generate(root: &Utf8Path) -> Result<()> {
    let dir = root.join("reference");
    std::fs::create_dir_all(&dir).with_context(|| format!("creating {dir}"))?;
    let path = dir.join("events.md");

    let kinds = scan_kinds("crates").context("scanning crates for event kinds")?;

    let mut body = String::new();
    body.push_str("---\n");
    body.push_str("title: Events & tracing\n");
    body.push_str(
        "description: Catalog of structured events Versionx emits. \
         Auto-generated by scanning every emit callsite across the workspace.\n",
    );
    body.push_str("sidebar_position: 6\n");
    body.push_str("---\n\n");
    body.push_str(&banner("events"));
    body.push_str("\n# Events & tracing\n\n");
    body.push_str(
        "Every Versionx operation emits structured events. The same stream \
         feeds the CLI's progress output, the TUI dashboard, the daemon's \
         RPC notifications (forwarded to CLI/TUI/web/MCP clients), OTLP \
         export, and the state DB's run history.\n\n",
    );

    body.push_str("## Enabling\n\n");
    body.push_str("### On stderr (human-friendly)\n\n");
    body.push_str("```bash\nVERSIONX_LOG=debug versionx sync\n```\n\n");
    body.push_str("### As newline-delimited JSON\n\n");
    body.push_str("```bash\nversionx sync --output ndjson | jq\n```\n\n");
    body.push_str("### Over OTLP\n\n");
    body.push_str(
        "```bash\nexport VERSIONX_OTLP_ENDPOINT=http://localhost:4317\nversionx sync\n```\n\n",
    );

    body.push_str("## Event shape\n\n");
    body.push_str("```json\n");
    body.push_str("{\n");
    body.push_str("  \"id\": \"uuid-v7\",\n");
    body.push_str("  \"timestamp\": \"2026-04-18T14:02:17.123Z\",\n");
    body.push_str("  \"kind\": \"adapter.exec.stdout\",\n");
    body.push_str("  \"level\": \"info\",\n");
    body.push_str("  \"message\": \"pnpm install\",\n");
    body.push_str("  \"data\": { }\n");
    body.push_str("}\n");
    body.push_str("```\n\n");

    body.push_str("## Kinds emitted today\n\n");
    if kinds.is_empty() {
        body.push_str("_No kinds detected — scanner may need updating._\n");
    } else {
        body.push_str(&format!(
            "Scanner found **{}** distinct kinds across the workspace, \
             grouped below by top-level category.\n\n",
            kinds.values().map(BTreeSet::len).sum::<usize>(),
        ));
        for (category, items) in &kinds {
            body.push_str(&format!("### `{category}`\n\n"));
            for kind in items {
                body.push_str(&format!("- `{kind}`\n"));
            }
            body.push('\n');
        }
    }

    body.push_str("## Consumption\n\n");
    body.push_str("### From an AI agent\n\n");
    body.push_str(
        "Agents connected via [MCP](/integrations/mcp/overview) receive \
         events as progress notifications on streaming tool calls.\n\n",
    );
    body.push_str("### From Rust (SDK)\n\n");
    body.push_str("```rust\n");
    body.push_str("use versionx_sdk::{Core, EventBus};\n\n");
    body.push_str("let bus = EventBus::new();\n");
    body.push_str("let mut rx = bus.subscribe();\n");
    body.push_str("let core = Core::builder().event_bus(bus).build().await?;\n\n");
    body.push_str("tokio::spawn(async move {\n");
    body.push_str("    while let Ok(event) = rx.recv().await {\n");
    body.push_str("        if event.kind.starts_with(\"policy.\") {\n");
    body.push_str("            eprintln!(\"{event:?}\");\n");
    body.push_str("        }\n");
    body.push_str("    }\n");
    body.push_str("});\n");
    body.push_str("```\n\n");
    body.push_str("### From a shell\n\n");
    body.push_str("```bash\n");
    body.push_str("versionx sync --output ndjson \\\n");
    body.push_str("  | jq 'select(.kind | startswith(\"adapter.\"))'\n");
    body.push_str("```\n\n");

    body.push_str("## See also\n\n");
    body.push_str(
        "- [Design principles](/introduction/design-principles) — principle 8, observability.\n",
    );
    body.push_str(
        "- [Environment variables](./environment-variables) — `VERSIONX_OTLP_*` settings.\n",
    );

    std::fs::write(&path, body).with_context(|| format!("writing {path}"))?;
    eprintln!("docs-events: wrote {path} ({} categories)", kinds.len());
    Ok(())
}

/// Scan every `.rs` file under `root` for event-emission call sites and
/// return the set of kinds grouped by top-level category.
fn scan_kinds(root: &str) -> Result<BTreeMap<String, BTreeSet<String>>> {
    // Patterns we look for:
    //   Event::new("kind.something"
    //   .info("kind.something"
    //   .warn("kind.something"
    //   .emit(Event::new("kind.something"
    //
    // A "kind" must contain at least one dot (that's the convention) and
    // match [a-z0-9_.:-]+ to avoid catching arbitrary strings.
    let pattern = Regex::new(
        r#"(?:Event::new|\.info|\.warn|\.debug|\.trace|\.error)\s*\(\s*"([a-z][a-z0-9_.:-]*\.[a-z0-9_.:-]+)""#,
    )
    .context("compiling events regex")?;

    let mut by_category: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();

    for entry in WalkDir::new(root).into_iter().filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("rs") {
            continue;
        }
        // Skip xtask itself and test files.
        let p = path.to_string_lossy();
        if p.contains("/xtask/") {
            continue;
        }
        let content = match std::fs::read_to_string(path) {
            Ok(c) => c,
            Err(_) => continue,
        };
        // Drop anything past a `#[cfg(test)]` module marker at column 0 —
        // test kinds are noise in a user-facing catalog.
        let effective = match content.find("\n#[cfg(test)]\nmod tests") {
            Some(idx) => &content[..idx],
            None => &content[..],
        };
        for cap in pattern.captures_iter(effective) {
            let kind = cap.get(1).map_or("", |m| m.as_str()).to_string();
            let category = kind.split('.').next().unwrap_or("misc").to_string();
            by_category.entry(category).or_default().insert(kind);
        }
    }

    Ok(by_category)
}
