//! Documentation generators.
//!
//! Each submodule regenerates an auto-generated page under
//! `website/docs/`. The top-level `docs` subcommand fans out to all of them.
//!
//! Generated files carry a banner so hand edits are obviously wrong.
//! CI enforces `git diff --exit-code` after running these, so drift fails
//! the build.

use anyhow::{Context, Result};
use camino::Utf8PathBuf;
use clap::{Args, ValueEnum};

mod cli;
mod config;
mod events;
mod exit_codes;
mod mcp;
mod rpc;

#[derive(Args, Debug)]
pub(crate) struct DocsArgs {
    /// Regenerate only a specific section.
    #[arg(long, value_enum)]
    only: Option<Section>,

    /// Write generated output to a custom directory instead of `website/docs/`.
    #[arg(long)]
    out: Option<Utf8PathBuf>,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub(crate) enum Section {
    Cli,
    Config,
    Events,
    ExitCodes,
    Mcp,
    Rpc,
}

pub(crate) fn run(args: DocsArgs) -> Result<()> {
    let root = args
        .out
        .unwrap_or_else(|| Utf8PathBuf::from("website").join("docs"));
    std::fs::create_dir_all(&root).with_context(|| format!("creating {root}"))?;

    match args.only {
        Some(Section::Cli) => cli::generate(&root),
        Some(Section::Config) => config::generate(&root),
        Some(Section::Events) => events::generate(&root),
        Some(Section::ExitCodes) => exit_codes::generate(&root),
        Some(Section::Mcp) => mcp::generate(&root),
        Some(Section::Rpc) => rpc::generate(&root),
        None => {
            cli::generate(&root)?;
            config::generate(&root)?;
            events::generate(&root)?;
            exit_codes::generate(&root)?;
            mcp::generate(&root)?;
            rpc::generate(&root)?;
            Ok(())
        }
    }
}

/// Standard banner every generated file carries.
pub(crate) fn banner(generator: &str) -> String {
    format!(
        "{{/* GENERATED by `cargo xtask docs-{generator}`. Do not edit by hand. */}}\n\
         {{/* Generated at {now} */}}\n",
        now = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ")
    )
}
