//! Documentation generators.
//!
//! Each submodule regenerates an auto-generated page under
//! `website/docs/`. The top-level `docs` subcommand fans out to all of them.
//!
//! Generated pages are the single source of truth for Reference material —
//! hand edits get clobbered on the next run. CI enforces `git diff
//! --exit-code` after running these, so drift fails the build.

// These generators build up Markdown tables by pushing many format!(...)
// strings onto a buffer. Clippy's pedantic / nursery lints prefer
// `write!(buf, ...)` everywhere, but since this is a build-time tool the
// readability tradeoff isn't worth it. Silence the noisy ones at module
// root.
#![allow(
    clippy::format_push_string,
    clippy::uninlined_format_args,
    clippy::manual_let_else,
    clippy::redundant_closure_for_method_calls,
    clippy::unnecessary_trailing_comma,
    clippy::useless_format,
    clippy::collapsible_if,
    clippy::missing_const_for_fn,
    clippy::use_self,
    clippy::map_unwrap_or,
    clippy::option_if_let_else,
    clippy::too_many_lines,
    clippy::items_after_statements
)]

use anyhow::{Context, Result};
use camino::Utf8PathBuf;
use clap::{Args, ValueEnum};

mod cli;
mod config;
mod events;
mod exit_codes;
mod mcp;
mod rpc;
pub(crate) mod syn_util;

#[derive(Args, Debug)]
pub(crate) struct DocsArgs {
    /// Regenerate only a specific section.
    #[arg(long, value_enum)]
    only: Option<Section>,

    /// Write generated output to a custom directory instead of `website/docs/`.
    #[arg(long)]
    out: Option<Utf8PathBuf>,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub(crate) enum Section {
    Cli,
    Config,
    Events,
    ExitCodes,
    Mcp,
    Rpc,
}

pub(crate) fn run(args: DocsArgs) -> Result<()> {
    let root = args.out.unwrap_or_else(|| Utf8PathBuf::from("website").join("docs"));
    std::fs::create_dir_all(&root).with_context(|| format!("creating {root}"))?;

    match args.only {
        Some(Section::Cli) => cli::generate(&root),
        Some(Section::Config) => config::generate(&root),
        Some(Section::Events) => events::generate(&root),
        Some(Section::ExitCodes) => exit_codes::generate(&root),
        Some(Section::Mcp) => mcp::generate(&root),
        Some(Section::Rpc) => rpc::generate(&root),
        None => {
            cli::generate(&root)?;
            config::generate(&root)?;
            events::generate(&root)?;
            exit_codes::generate(&root)?;
            mcp::generate(&root)?;
            rpc::generate(&root)?;
            Ok(())
        }
    }
}

/// Standard banner at the top of every generated file body.
pub(crate) fn banner(generator: &str) -> String {
    format!("{{/* GENERATED by `cargo xtask docs --only {generator}`. Do not edit by hand. */}}\n")
}
