import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      link: {type: 'doc', id: 'introduction/what-is-versionx'},
      items: [
        'introduction/what-is-versionx',
        'introduction/how-it-compares',
        'introduction/status-and-roadmap',
        'introduction/design-principles',
      ],
    },
    {
      type: 'category',
      label: 'Get started',
      link: {type: 'doc', id: 'get-started/install'},
      items: [
        'get-started/install',
        'get-started/quickstart',
        'get-started/your-first-release',
        {
          type: 'category',
          label: 'Migrate',
          items: [
            'get-started/migrate-from-mise',
            'get-started/migrate-from-asdf',
            'get-started/migrate-from-changesets',
            'get-started/migrate-from-release-please',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'guides/managing-toolchains'},
      items: [
        'guides/managing-toolchains',
        'guides/polyglot-dependency-updates',
        'guides/orchestrating-a-release',
        'guides/multi-repo-and-monorepos',
        'guides/policy-and-waivers',
        'guides/daemon-and-tui',
        'guides/github-actions-recipes',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'doc', id: 'reference/overview'},
      items: [
        {
          type: 'category',
          label: 'CLI',
          link: {type: 'doc', id: 'reference/cli/versionx'},
          items: [{type: 'autogenerated', dirName: 'reference/cli'}],
        },
        'reference/versionx-toml',
        'reference/versionx-lock',
        'reference/state-db-schema',
        'reference/events',
        'reference/exit-codes',
        'reference/environment-variables',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {type: 'doc', id: 'integrations/mcp/overview'},
      items: [
        {
          type: 'category',
          label: 'MCP',
          link: {type: 'doc', id: 'integrations/mcp/overview'},
          items: [
            'integrations/mcp/overview',
            'integrations/mcp/claude-code',
            'integrations/mcp/cursor',
            'integrations/mcp/codex',
            'integrations/mcp/qwen',
            'integrations/mcp/ollama',
            'integrations/mcp/tool-catalog',
          ],
        },
        'integrations/json-rpc-daemon',
        'integrations/http-api',
        'integrations/github-actions',
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      link: {type: 'doc', id: 'sdk/overview'},
      items: [
        'sdk/overview',
        'sdk/embedding',
        'sdk/plan-apply-cookbook',
        'sdk/custom-adapters',
        'sdk/rustdoc',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      link: {type: 'doc', id: 'contributing/dev-environment'},
      items: [
        'contributing/dev-environment',
        'contributing/workspace-tour',
        'contributing/architecture',
        'contributing/adding-a-package-manager-adapter',
        'contributing/adding-a-runtime-installer',
        'contributing/writing-tests',
        'contributing/debugging-and-tracing',
        'contributing/release-engineering',
        'contributing/rfcs-and-design-docs',
      ],
    },
    'roadmap',
  ],
};

export default sidebars;
